# =============================================================================
# generator
# =============================================================================
GEN_DATASET_CFG:
    DATASET_PATH: ['ori_data', 1, 'pcd+txt原始数据集文件的路径']
    CONFIG_FILE_PATH: ['config_file', 1, '配置文件的路径']
    INCLUDE_SCENE_LIST: [[], 2, '包含的场景文件名称']
    TRANSLATION_LIST: [[] , 2, '每个场景下的偏移向量,亦即统一坐标原点(如车辆后轴中心)在当前坐标系下的坐标']
    RATIO: [0.8175, 2, '训练集样本占数据集的比例']
    REGENERATE: [True, 2, '是否重新生成数据集配置文件']