# =============================================================================
# dataset filter
# =============================================================================
DATASET_FILTER: 
    ORI_DATA: ['ori_data', 1, '数据集加载路径(文件夹名)']
    INCLUDE_SCENE: [[], 2, '包含的数据集场景名(文件名)']
    INCLUDE_PREFIX: [[], 2, '包含的数据集场景名(文件名)前缀']
    INCLUDE_SUFFIX: [['cloud'], 2, '包含的数据集场景名(文件名)后缀']
    EXCLUDE_SCENE: [[], 2, '需要剔除的数据集场景名(文件名)']
    EXCLUDE_PREFIX: [[], 2, '需要剔除的数据集场景名(文件名)前缀']
    EXCLUDE_SUFFIX: [[], 2, '需要剔除的数据集场景名(文件名)后缀']
  