# =============================================================================
# partition
# =============================================================================
PARTITION:
    ORI_DATA: ['ori_data', 1, '数据集加载路径(文件夹名)']
    OUTPUT: ['middle_data\partition_output', 1, '文件保存路径']
    RATIO: [0.1, 2, '测试集在数据集中的占比']
    SHUFFLE_INDEX: [0, 2, '数据集乱序层级(0:点云簇乱序; 1:单帧乱序; 2:场景乱序)']
    EXTRA_SUFFIX: [[], 0, '保存文件名称后缀']
    REGENERATE: [True, 2, '数据集是否重新生成:删除/融合本地已有的保存文件']
    SEED: [100, 0, '随机种子:多次随机结果一致']